# Generated by Django 2.0.5 on 2018-06-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winter_olympics_2018', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='noc',
            field=models.CharField(max_length=10),
        ),
    ]
