# Generated by Django 2.0.5 on 2018-06-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winter_olympics_2018', '0002_auto_20180622_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='noc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='country',
            name='short',
            field=models.CharField(max_length=255),
        ),
    ]
